export type YesNo = 'Yes' | 'No';

export type EppScenarioData = {
  scenarioId: string;
  applicationType: 'Apply for a new licence' | 'Renew a licence' | 'Amend a licence' | 'Replace a licence';
  otherNames: YesNo | 'N/A';
  replacementReason: string;
  theftReported: YesNo | 'N/A';
  detailsChanged: YesNo | 'N/A';
  amendName: YesNo | 'N/A';
  moreNationalities: YesNo | 'N/A';
  sex: 'Male' | 'Female' | 'X or other' | 'N/A';
  identityDocument: string;
  amendHomeAddress: YesNo | 'N/A';
  amendSubstance: YesNo | 'N/A';
  amendExplosivesPrecursors: YesNo | 'N/A';
  firearmsLicence: YesNo | 'N/A';
  shotgunLicence: YesNo | 'N/A';
  refusedRevoked: YesNo | 'N/A';
  criminalRecord: YesNo | 'N/A';
  seenDoctor: YesNo | 'N/A';
  treatmentDrugAlcohol: YesNo | 'N/A';
  coverExplosivesPrecursors: YesNo | 'N/A';
  explosivePrecursor: string;
  storeAmmonium: string;
  useAmmonium: string;
  amendPoisons: YesNo | 'N/A';
  continueWithoutChanges: YesNo | 'N/A';
  coverPoisons: YesNo | 'N/A';
  poison: string;
  useDnp: string;
  storeDnp: string;
  countersignatoryIdentityDocument: string;
};

const scenarios: Record<string, EppScenarioData> = {
  '1': {
    scenarioId: '1',
    applicationType: 'Apply for a new licence',
    otherNames: 'No',
    replacementReason: 'N/A',
    theftReported: 'N/A',
    detailsChanged: 'N/A',
    amendName: 'N/A',
    moreNationalities: 'No',
    sex: 'Male',
    identityDocument: 'British passport',
    amendHomeAddress: 'N/A',
    amendSubstance: 'N/A',
    amendExplosivesPrecursors: 'N/A',
    firearmsLicence: 'No',
    shotgunLicence: 'No',
    refusedRevoked: 'No',
    criminalRecord: 'No',
    seenDoctor: 'No',
    treatmentDrugAlcohol: 'No',
    coverExplosivesPrecursors: 'No',
    explosivePrecursor: 'Hexamine',
    storeAmmonium: 'Home address',
    useAmmonium: 'Other address',
    amendPoisons: 'N/A',
    continueWithoutChanges: 'N/A',
    coverPoisons: 'No',
    poison: '2,4-dinitrophenol and its compounds including dinitrophenolate',
    useDnp: 'Home address',
    storeDnp: 'Home address',
    countersignatoryIdentityDocument: 'British passport',
  },
  '2': {
    scenarioId: '2',
    applicationType: 'Apply for a new licence',
    otherNames: 'Yes',
    replacementReason: 'N/A',
    theftReported: 'N/A',
    detailsChanged: 'N/A',
    amendName: 'N/A',
    moreNationalities: 'Yes',
    sex: 'Female',
    identityDocument: 'Passport from the EU, Switzerland, Norway, Iceland or Liechtenstein',
    amendHomeAddress: 'N/A',
    amendSubstance: 'N/A',
    amendExplosivesPrecursors: 'N/A',
    firearmsLicence: 'Yes',
    shotgunLicence: 'Yes',
    refusedRevoked: 'Yes',
    criminalRecord: 'Yes',
    seenDoctor: 'Yes',
    treatmentDrugAlcohol: 'Yes',
    coverExplosivesPrecursors: 'Yes',
    explosivePrecursor: 'Nitric acid above 3% (weight by weight)',
    storeAmmonium: 'Other address',
    useAmmonium: 'Home address',
    amendPoisons: 'N/A',
    continueWithoutChanges: 'N/A',
    coverPoisons: 'Yes',
    poison: 'Barium salts',
    useDnp: 'Other address',
    storeDnp: 'Other address',
    countersignatoryIdentityDocument: 'Passport from the EU, Switzerland, Norway, Iceland or Liechtenstein',
  },
  '3': {
    scenarioId: '3',
    applicationType: 'Apply for a new licence',
    otherNames: 'No',
    replacementReason: 'N/A',
    theftReported: 'N/A',
    detailsChanged: 'N/A',
    amendName: 'N/A',
    moreNationalities: 'No',
    sex: 'X or other',
    identityDocument: 'UK driving licence',
    amendHomeAddress: 'N/A',
    amendSubstance: 'N/A',
    amendExplosivesPrecursors: 'N/A',
    firearmsLicence: 'No',
    shotgunLicence: 'No',
    refusedRevoked: 'No',
    criminalRecord: 'No',
    seenDoctor: 'No',
    treatmentDrugAlcohol: 'No',
    coverExplosivesPrecursors: 'No',
    explosivePrecursor: 'Potassium perchlorate above 40% (weight by weight)',
    storeAmmonium: 'Home address',
    useAmmonium: 'Home address',
    amendPoisons: 'N/A',
    continueWithoutChanges: 'N/A',
    coverPoisons: 'Yes',
    poison: 'Calcium phosphide',
    useDnp: 'Home address',
    storeDnp: 'Home address',
    countersignatoryIdentityDocument: 'UK driving licence',
  },
  '4': {
    scenarioId: '4',
    applicationType: 'Renew a licence',
    otherNames: 'No',
    replacementReason: 'N/A',
    theftReported: 'N/A',
    detailsChanged: 'N/A',
    amendName: 'N/A',
    moreNationalities: 'No',
    sex: 'Male',
    identityDocument: 'British passport',
    amendHomeAddress: 'N/A',
    amendSubstance: 'N/A',
    amendExplosivesPrecursors: 'N/A',
    firearmsLicence: 'Yes',
    shotgunLicence: 'No',
    refusedRevoked: 'No',
    criminalRecord: 'Yes',
    seenDoctor: 'No',
    treatmentDrugAlcohol: 'No',
    coverExplosivesPrecursors: 'Yes',
    explosivePrecursor: 'Sodium perchlorate above 40% (weight by weight)',
    storeAmmonium: 'Home address',
    useAmmonium: 'Other address',
    amendPoisons: 'N/A',
    continueWithoutChanges: 'N/A',
    coverPoisons: 'No',
    poison: 'Hydrogen cyanide and metal cyanides',
    useDnp: 'Other address',
    storeDnp: 'Home address',
    countersignatoryIdentityDocument: 'Passport from the EU, Switzerland, Norway, Iceland or Liechtenstein',
  },
  '5': {
    scenarioId: '5',
    applicationType: 'Renew a licence',
    otherNames: 'Yes',
    replacementReason: 'N/A',
    theftReported: 'N/A',
    detailsChanged: 'N/A',
    amendName: 'N/A',
    moreNationalities: 'No',
    sex: 'Female',
    identityDocument: 'Passport from the EU, Switzerland, Norway, Iceland or Liechtenstein',
    amendHomeAddress: 'N/A',
    amendSubstance: 'N/A',
    amendExplosivesPrecursors: 'N/A',
    firearmsLicence: 'No',
    shotgunLicence: 'Yes',
    refusedRevoked: 'Yes',
    criminalRecord: 'No',
    seenDoctor: 'Yes',
    treatmentDrugAlcohol: 'Yes',
    coverExplosivesPrecursors: 'No',
    explosivePrecursor: 'Potassium perchlorate above 40% (weight by weight)',
    storeAmmonium: 'Other address',
    useAmmonium: 'Home address',
    amendPoisons: 'N/A',
    continueWithoutChanges: 'N/A',
    coverPoisons: 'Yes',
    poison: 'Magnesium phosphide',
    useDnp: 'Home address',
    storeDnp: 'Other address',
    countersignatoryIdentityDocument: 'British passport',
  },
  '6': {
    scenarioId: '6',
    applicationType: 'Renew a licence',
    otherNames: 'No',
    replacementReason: 'N/A',
    theftReported: 'N/A',
    detailsChanged: 'N/A',
    amendName: 'N/A',
    moreNationalities: 'Yes',
    sex: 'X or other',
    identityDocument: 'UK driving licence',
    amendHomeAddress: 'N/A',
    amendSubstance: 'N/A',
    amendExplosivesPrecursors: 'N/A',
    firearmsLicence: 'Yes',
    shotgunLicence: 'No',
    refusedRevoked: 'No',
    criminalRecord: 'No',
    seenDoctor: 'Yes',
    treatmentDrugAlcohol: 'No',
    coverExplosivesPrecursors: 'No',
    explosivePrecursor: 'Sodium perchlorate above 40% (weight by weight)',
    storeAmmonium: 'Other address',
    useAmmonium: 'Home address',
    amendPoisons: 'N/A',
    continueWithoutChanges: 'N/A',
    coverPoisons: 'No',
    poison: 'Calcium phosphide',
    useDnp: 'Other address',
    storeDnp: 'Home address',
    countersignatoryIdentityDocument: 'UK driving licence',
  },
  '7': {
    scenarioId: '7',
    applicationType: 'Amend a licence',
    otherNames: 'N/A',
    replacementReason: 'N/A',
    theftReported: 'N/A',
    detailsChanged: 'N/A',
    amendName: 'Yes',
    moreNationalities: 'N/A',
    sex: 'N/A',
    identityDocument: 'British passport',
    amendHomeAddress: 'Yes',
    amendSubstance: 'Yes',
    amendExplosivesPrecursors: 'Yes',
    firearmsLicence: 'N/A',
    shotgunLicence: 'N/A',
    refusedRevoked: 'N/A',
    criminalRecord: 'N/A',
    seenDoctor: 'N/A',
    treatmentDrugAlcohol: 'N/A',
    coverExplosivesPrecursors: 'N/A',
    explosivePrecursor: 'Sodium perchlorate above 40% (weight by weight)',
    storeAmmonium: 'Home address',
    useAmmonium: 'Other address',
    amendPoisons: 'Yes',
    continueWithoutChanges: 'Yes',
    coverPoisons: 'N/A',
    poison: 'Bromomethane',
    useDnp: 'Other address',
    storeDnp: 'Home address',
    countersignatoryIdentityDocument: 'Passport from the EU, Switzerland, Norway, Iceland or Liechtenstein',
  },
  '8': {
    scenarioId: '8',
    applicationType: 'Amend a licence',
    otherNames: 'N/A',
    replacementReason: 'N/A',
    theftReported: 'N/A',
    detailsChanged: 'N/A',
    amendName: 'No',
    moreNationalities: 'N/A',
    sex: 'N/A',
    identityDocument: 'UK driving licence',
    amendHomeAddress: 'Yes',
    amendSubstance: 'No',
    amendExplosivesPrecursors: 'No',
    firearmsLicence: 'N/A',
    shotgunLicence: 'N/A',
    refusedRevoked: 'N/A',
    criminalRecord: 'N/A',
    seenDoctor: 'N/A',
    treatmentDrugAlcohol: 'N/A',
    coverExplosivesPrecursors: 'N/A',
    explosivePrecursor: 'N/A',
    storeAmmonium: 'N/A',
    useAmmonium: 'N/A',
    amendPoisons: 'No',
    continueWithoutChanges: 'N/A',
    coverPoisons: 'N/A',
    poison: 'Mercury and its compounds',
    useDnp: 'Home address',
    storeDnp: 'Other address',
    countersignatoryIdentityDocument: 'UK driving licence',
  },
  '9': {
    scenarioId: '9',
    applicationType: 'Replace a licence',
    otherNames: 'N/A',
    replacementReason: 'Licence was stolen',
    theftReported: 'Yes',
    detailsChanged: 'Yes',
    amendName: 'Yes',
    moreNationalities: 'N/A',
    sex: 'N/A',
    identityDocument: 'Passport from the EU, Switzerland, Norway, Iceland or Liechtenstein',
    amendHomeAddress: 'Yes',
    amendSubstance: 'Yes',
    amendExplosivesPrecursors: 'Yes',
    firearmsLicence: 'N/A',
    shotgunLicence: 'N/A',
    refusedRevoked: 'N/A',
    criminalRecord: 'N/A',
    seenDoctor: 'N/A',
    treatmentDrugAlcohol: 'N/A',
    coverExplosivesPrecursors: 'N/A',
    explosivePrecursor: 'Nitromethane above 30% (weight by weight)',
    storeAmmonium: 'Home address',
    useAmmonium: 'Other address',
    amendPoisons: 'Yes',
    continueWithoutChanges: 'N/A',
    coverPoisons: 'N/A',
    poison: 'Thallium and its salts',
    useDnp: 'Other address',
    storeDnp: 'Home address',
    countersignatoryIdentityDocument: 'British passport',
  },
  '10': {
    scenarioId: '10',
    applicationType: 'Replace a licence',
    otherNames: 'N/A',
    replacementReason: 'Licence is lost',
    theftReported: 'No',
    detailsChanged: 'No',
    amendName: 'No',
    moreNationalities: 'N/A',
    sex: 'N/A',
    identityDocument: 'British passport',
    amendHomeAddress: 'No',
    amendSubstance: 'No',
    amendExplosivesPrecursors: 'No',
    firearmsLicence: 'N/A',
    shotgunLicence: 'N/A',
    refusedRevoked: 'N/A',
    criminalRecord: 'N/A',
    seenDoctor: 'N/A',
    treatmentDrugAlcohol: 'N/A',
    coverExplosivesPrecursors: 'N/A',
    explosivePrecursor: 'Sulfuric acid above 15% (weight by weight)',
    storeAmmonium: 'Other address',
    useAmmonium: 'Home address',
    amendPoisons: 'No',
    continueWithoutChanges: 'N/A',
    coverPoisons: 'N/A',
    poison: 'Zinc phosphide',
    useDnp: 'Home address',
    storeDnp: 'Other address',
    countersignatoryIdentityDocument: 'EEA passport',
  },
  '11': {
    scenarioId: '11',
    applicationType: 'Replace a licence',
    otherNames: 'N/A',
    replacementReason: 'Licence is damaged',
    theftReported: 'No',
    detailsChanged: 'Yes',
    amendName: 'No',
    moreNationalities: 'N/A',
    sex: 'N/A',
    identityDocument: 'UK driving licence',
    amendHomeAddress: 'Yes',
    amendSubstance: 'No',
    amendExplosivesPrecursors: 'Yes',
    firearmsLicence: 'N/A',
    shotgunLicence: 'N/A',
    refusedRevoked: 'N/A',
    criminalRecord: 'N/A',
    seenDoctor: 'N/A',
    treatmentDrugAlcohol: 'N/A',
    coverExplosivesPrecursors: 'N/A',
    explosivePrecursor: 'Phosphoric acid above 30% (weight by weight)',
    storeAmmonium: 'Home address',
    useAmmonium: 'Other address',
    amendPoisons: 'Yes',
    continueWithoutChanges: 'N/A',
    coverPoisons: 'N/A',
    poison: 'Chloropicrin',
    useDnp: 'Other address',
    storeDnp: 'Home address',
    countersignatoryIdentityDocument: 'UK driving licence',
  },
};

export function getEppScenarioData(scenarioId: string): EppScenarioData {
  const scenario = scenarios[scenarioId];
  if (!scenario) {
    throw new Error(`Invalid EPP scenario id: ${scenarioId}`);
  }
  return scenario;
}