export type EppScenarioData = {
  scenarioId: string;
  whatTypeOfApplicationDoYouNeedToMake: string;
  haveYouEverUsedAnyOtherNames: string;
  whyDoYouNeedAReplacementLicence: string;
  haveYouReportedTheTheftToPolice: string;
  haveAnyOfYourDetailsChangedSinceLicence: string;
  doYouNeedToAmendYourNameOnTheLicence: string;
  doYouHaveMoreThanOneNationality: string;
  whatIsYourSex: string;
  whichIdentityDocumentDoYouWantToUse: string;
  doYouNeedToAmendYourHomeAddressOnTheLicence: string;
  doYouNeedToAmendTheSubstanceOnYourLicence: string;
  doYouNeedToAmendTheExplosivesPrecursorsOnYourLicence: string;
  doYouHaveOrHaveYouEverHadAFirearmsLicence: string;
  doYouHaveOrHaveYouEverHadAShotgunLicence: string;
  haveYouEverHadAShotgunOrFirearmsLicenceRefusedOrRevoked: string;
  doYouHaveACriminalRecord: string;
  inTheLast10YearsHaveYouSeenADoctor: string;
  haveYouEverHadOrReceivedTreatmentForAnyDrugOrAlcoholrelatedHealthProblems: string;
  doesYourLicenceNeedToCoverExplosivesPrecursors: string;
  selectAnExplosivesPrecursor: string;
  whereWillYouStoreTheAmmoniumNitrate: string;
  whereWillYouUseTheAmmoniumNitrate: string;
  doYouNeedToAmendThePoisonsOnYourLicence: string;
  doYouWantToContinueTheFormWithoutChangingTheEpp: string;
  doesYourLicenceNeedToCoverPoisons: string;
  tellUsWhichPoisonsYouWantToImportAcquireUseOrPossess: string;
  whereWillYouUseTheDnp: string;
  whereWillYouStoreTheDnp: string;
  whatIsYourCountersignatorysIdentityDocument: string;
};

const S = (data: Omit<EppScenarioData, 'scenarioId'>, scenarioId: string): EppScenarioData => ({ scenarioId, ...data });

const scenarios: Record<string, EppScenarioData> = {
  '1': S({
    whatTypeOfApplicationDoYouNeedToMake: 'Apply for a new licence',
    haveYouEverUsedAnyOtherNames: 'No',
    whyDoYouNeedAReplacementLicence: 'N/A',
    haveYouReportedTheTheftToPolice: 'N/A',
    haveAnyOfYourDetailsChangedSinceLicence: 'N/A',
    doYouNeedToAmendYourNameOnTheLicence: 'N/A',
    doYouHaveMoreThanOneNationality: 'No',
    whatIsYourSex: 'Male',
    whichIdentityDocumentDoYouWantToUse: 'British passport',
    doYouNeedToAmendYourHomeAddressOnTheLicence: 'N/A',
    doYouNeedToAmendTheSubstanceOnYourLicence: 'N/A',
    doYouNeedToAmendTheExplosivesPrecursorsOnYourLicence: 'N/A',
    doYouHaveOrHaveYouEverHadAFirearmsLicence: 'No',
    doYouHaveOrHaveYouEverHadAShotgunLicence: 'No',
    haveYouEverHadAShotgunOrFirearmsLicenceRefusedOrRevoked: 'No',
    doYouHaveACriminalRecord: 'No',
    inTheLast10YearsHaveYouSeenADoctor: 'No',
    haveYouEverHadOrReceivedTreatmentForAnyDrugOrAlcoholrelatedHealthProblems: 'No',
    doesYourLicenceNeedToCoverExplosivesPrecursors: 'No',
    selectAnExplosivesPrecursor: 'Hexamine',
    whereWillYouStoreTheAmmoniumNitrate: 'Home address',
    whereWillYouUseTheAmmoniumNitrate: 'Other address',
    doYouNeedToAmendThePoisonsOnYourLicence: 'N/A',
    doYouWantToContinueTheFormWithoutChangingTheEpp: 'N/A',
    doesYourLicenceNeedToCoverPoisons: 'No',
    tellUsWhichPoisonsYouWantToImportAcquireUseOrPossess: '2,4- Dinitrophenol and derivatives including sodium dinitrophenolate',
    whereWillYouUseTheDnp: 'Home address',
    whereWillYouStoreTheDnp: 'Home address',
    whatIsYourCountersignatorysIdentityDocument: 'British passport',
  }, '1'),
  '2': S({
    whatTypeOfApplicationDoYouNeedToMake: 'Apply for a new licence',
    haveYouEverUsedAnyOtherNames: 'Yes',
    whyDoYouNeedAReplacementLicence: 'N/A',
    haveYouReportedTheTheftToPolice: 'N/A',
    haveAnyOfYourDetailsChangedSinceLicence: 'N/A',
    doYouNeedToAmendYourNameOnTheLicence: 'N/A',
    doYouHaveMoreThanOneNationality: 'Yes',
    whatIsYourSex: 'Female',
    whichIdentityDocumentDoYouWantToUse: 'Passport from the EU, Switzerland, Norway, Iceland or Liechtenstein',
    doYouNeedToAmendYourHomeAddressOnTheLicence: 'N/A',
    doYouNeedToAmendTheSubstanceOnYourLicence: 'N/A',
    doYouNeedToAmendTheExplosivesPrecursorsOnYourLicence: 'N/A',
    doYouHaveOrHaveYouEverHadAFirearmsLicence: 'Yes',
    doYouHaveOrHaveYouEverHadAShotgunLicence: 'Yes',
    haveYouEverHadAShotgunOrFirearmsLicenceRefusedOrRevoked: 'Yes',
    doYouHaveACriminalRecord: 'Yes',
    inTheLast10YearsHaveYouSeenADoctor: 'Yes',
    haveYouEverHadOrReceivedTreatmentForAnyDrugOrAlcoholrelatedHealthProblems: 'Yes',
    doesYourLicenceNeedToCoverExplosivesPrecursors: 'Yes',
    selectAnExplosivesPrecursor: 'Nitric acid above 3% (weight by weight)',
    whereWillYouStoreTheAmmoniumNitrate: 'Other address',
    whereWillYouUseTheAmmoniumNitrate: 'Home address',
    doYouNeedToAmendThePoisonsOnYourLicence: 'N/A',
    doYouWantToContinueTheFormWithoutChangingTheEpp: 'N/A',
    doesYourLicenceNeedToCoverPoisons: 'Yes',
    tellUsWhichPoisonsYouWantToImportAcquireUseOrPossess: 'Barium salts',
    whereWillYouUseTheDnp: 'Other address',
    whereWillYouStoreTheDnp: 'Other address',
    whatIsYourCountersignatorysIdentityDocument: 'Passport from the EU, Switzerland, Norway, Iceland or Liechtenstein',
  }, '2'),
  '3': S({
    whatTypeOfApplicationDoYouNeedToMake: 'Apply for a new licence',
    haveYouEverUsedAnyOtherNames: 'No',
    whyDoYouNeedAReplacementLicence: 'N/A',
    haveYouReportedTheTheftToPolice: 'N/A',
    haveAnyOfYourDetailsChangedSinceLicence: 'N/A',
    doYouNeedToAmendYourNameOnTheLicence: 'N/A',
    doYouHaveMoreThanOneNationality: 'No',
    whatIsYourSex: 'X or other',
    whichIdentityDocumentDoYouWantToUse: 'UK driving licence',
    doYouNeedToAmendYourHomeAddressOnTheLicence: 'N/A',
    doYouNeedToAmendTheSubstanceOnYourLicence: 'N/A',
    doYouNeedToAmendTheExplosivesPrecursorsOnYourLicence: 'N/A',
    doYouHaveOrHaveYouEverHadAFirearmsLicence: 'No',
    doYouHaveOrHaveYouEverHadAShotgunLicence: 'No',
    haveYouEverHadAShotgunOrFirearmsLicenceRefusedOrRevoked: 'No',
    doYouHaveACriminalRecord: 'No',
    inTheLast10YearsHaveYouSeenADoctor: 'No',
    haveYouEverHadOrReceivedTreatmentForAnyDrugOrAlcoholrelatedHealthProblems: 'No',
    doesYourLicenceNeedToCoverExplosivesPrecursors: 'No',
    selectAnExplosivesPrecursor: 'Potassium perchlorate above 40% (weight by weight)',
    whereWillYouStoreTheAmmoniumNitrate: 'Home address',
    whereWillYouUseTheAmmoniumNitrate: 'Home address',
    doYouNeedToAmendThePoisonsOnYourLicence: 'N/A',
    doYouWantToContinueTheFormWithoutChangingTheEpp: 'N/A',
    doesYourLicenceNeedToCoverPoisons: 'Yes',
    tellUsWhichPoisonsYouWantToImportAcquireUseOrPossess: 'Calcium phosphide',
    whereWillYouUseTheDnp: 'Home address',
    whereWillYouStoreTheDnp: 'Home address',
    whatIsYourCountersignatorysIdentityDocument: 'UK driving licence',
  }, '3'),
  '4': S({
    whatTypeOfApplicationDoYouNeedToMake: 'Renew a licence',
    haveYouEverUsedAnyOtherNames: 'No',
    whyDoYouNeedAReplacementLicence: 'N/A',
    haveYouReportedTheTheftToPolice: 'N/A',
    haveAnyOfYourDetailsChangedSinceLicence: 'N/A',
    doYouNeedToAmendYourNameOnTheLicence: 'N/A',
    doYouHaveMoreThanOneNationality: 'No',
    whatIsYourSex: 'Male',
    whichIdentityDocumentDoYouWantToUse: 'British passport',
    doYouNeedToAmendYourHomeAddressOnTheLicence: 'N/A',
    doYouNeedToAmendTheSubstanceOnYourLicence: 'N/A',
    doYouNeedToAmendTheExplosivesPrecursorsOnYourLicence: 'N/A',
    doYouHaveOrHaveYouEverHadAFirearmsLicence: 'Yes',
    doYouHaveOrHaveYouEverHadAShotgunLicence: 'No',
    haveYouEverHadAShotgunOrFirearmsLicenceRefusedOrRevoked: 'No',
    doYouHaveACriminalRecord: 'Yes',
    inTheLast10YearsHaveYouSeenADoctor: 'No',
    haveYouEverHadOrReceivedTreatmentForAnyDrugOrAlcoholrelatedHealthProblems: 'No',
    doesYourLicenceNeedToCoverExplosivesPrecursors: 'Yes',
    selectAnExplosivesPrecursor: 'Sodium perchlorate above 40% (weight by weight)',
    whereWillYouStoreTheAmmoniumNitrate: 'Home address',
    whereWillYouUseTheAmmoniumNitrate: 'Other address',
    doYouNeedToAmendThePoisonsOnYourLicence: 'N/A',
    doYouWantToContinueTheFormWithoutChangingTheEpp: 'N/A',
    doesYourLicenceNeedToCoverPoisons: 'No',
    tellUsWhichPoisonsYouWantToImportAcquireUseOrPossess: 'Hydrogen cyanide and metal cyanides',
    whereWillYouUseTheDnp: 'Other address',
    whereWillYouStoreTheDnp: 'Home address',
    whatIsYourCountersignatorysIdentityDocument: 'Passport from the EU, Switzerland, Norway, Iceland or Liechtenstein',
  }, '4'),
  '5': S({
    whatTypeOfApplicationDoYouNeedToMake: 'Renew a licence',
    haveYouEverUsedAnyOtherNames: 'Yes',
    whyDoYouNeedAReplacementLicence: 'N/A',
    haveYouReportedTheTheftToPolice: 'N/A',
    haveAnyOfYourDetailsChangedSinceLicence: 'N/A',
    doYouNeedToAmendYourNameOnTheLicence: 'N/A',
    doYouHaveMoreThanOneNationality: 'No',
    whatIsYourSex: 'Female',
    whichIdentityDocumentDoYouWantToUse: 'Passport from the EU, Switzerland, Norway, Iceland or Liechtenstein',
    doYouNeedToAmendYourHomeAddressOnTheLicence: 'N/A',
    doYouNeedToAmendTheSubstanceOnYourLicence: 'N/A',
    doYouNeedToAmendTheExplosivesPrecursorsOnYourLicence: 'N/A',
    doYouHaveOrHaveYouEverHadAFirearmsLicence: 'No',
    doYouHaveOrHaveYouEverHadAShotgunLicence: 'Yes',
    haveYouEverHadAShotgunOrFirearmsLicenceRefusedOrRevoked: 'Yes',
    doYouHaveACriminalRecord: 'No',
    inTheLast10YearsHaveYouSeenADoctor: 'Yes',
    haveYouEverHadOrReceivedTreatmentForAnyDrugOrAlcoholrelatedHealthProblems: 'Yes',
    doesYourLicenceNeedToCoverExplosivesPrecursors: 'No',
    selectAnExplosivesPrecursor: 'Potassium perchlorate above 40% (weight by weight)',
    whereWillYouStoreTheAmmoniumNitrate: 'Other address',
    whereWillYouUseTheAmmoniumNitrate: 'Home address',
    doYouNeedToAmendThePoisonsOnYourLicence: 'N/A',
    doYouWantToContinueTheFormWithoutChangingTheEpp: 'N/A',
    doesYourLicenceNeedToCoverPoisons: 'Yes',
    tellUsWhichPoisonsYouWantToImportAcquireUseOrPossess: 'Magnesium phosphide',
    whereWillYouUseTheDnp: 'Home address',
    whereWillYouStoreTheDnp: 'Other address',
    whatIsYourCountersignatorysIdentityDocument: 'British passport',
  }, '5'),
  '6': S({
    whatTypeOfApplicationDoYouNeedToMake: 'Renew a licence',
    haveYouEverUsedAnyOtherNames: 'No',
    whyDoYouNeedAReplacementLicence: 'N/A',
    haveYouReportedTheTheftToPolice: 'N/A',
    haveAnyOfYourDetailsChangedSinceLicence: 'N/A',
    doYouNeedToAmendYourNameOnTheLicence: 'N/A',
    doYouHaveMoreThanOneNationality: 'Yes',
    whatIsYourSex: 'X or other',
    whichIdentityDocumentDoYouWantToUse: 'UK driving licence',
    doYouNeedToAmendYourHomeAddressOnTheLicence: 'N/A',
    doYouNeedToAmendTheSubstanceOnYourLicence: 'N/A',
    doYouNeedToAmendTheExplosivesPrecursorsOnYourLicence: 'N/A',
    doYouHaveOrHaveYouEverHadAFirearmsLicence: 'Yes',
    doYouHaveOrHaveYouEverHadAShotgunLicence: 'No',
    haveYouEverHadAShotgunOrFirearmsLicenceRefusedOrRevoked: 'No',
    doYouHaveACriminalRecord: 'No',
    inTheLast10YearsHaveYouSeenADoctor: 'Yes',
    haveYouEverHadOrReceivedTreatmentForAnyDrugOrAlcoholrelatedHealthProblems: 'No',
    doesYourLicenceNeedToCoverExplosivesPrecursors: 'No',
    selectAnExplosivesPrecursor: 'Sodium perchlorate above 40% (weight by weight)',
    whereWillYouStoreTheAmmoniumNitrate: 'Other address',
    whereWillYouUseTheAmmoniumNitrate: 'Home address',
    doYouNeedToAmendThePoisonsOnYourLicence: 'N/A',
    doYouWantToContinueTheFormWithoutChangingTheEpp: 'N/A',
    doesYourLicenceNeedToCoverPoisons: 'No',
    tellUsWhichPoisonsYouWantToImportAcquireUseOrPossess: 'Calcium phosphide',
    whereWillYouUseTheDnp: 'Other address',
    whereWillYouStoreTheDnp: 'Home address',
    whatIsYourCountersignatorysIdentityDocument: 'UK driving licence',
  }, '6'),
  '7': S({
    whatTypeOfApplicationDoYouNeedToMake: 'Amend a licence',
    haveYouEverUsedAnyOtherNames: 'N/A',
    whyDoYouNeedAReplacementLicence: 'N/A',
    haveYouReportedTheTheftToPolice: 'N/A',
    haveAnyOfYourDetailsChangedSinceLicence: 'N/A',
    doYouNeedToAmendYourNameOnTheLicence: 'Yes',
    doYouHaveMoreThanOneNationality: 'N/A',
    whatIsYourSex: 'N/A',
    whichIdentityDocumentDoYouWantToUse: 'British passport',
    doYouNeedToAmendYourHomeAddressOnTheLicence: 'Yes',
    doYouNeedToAmendTheSubstanceOnYourLicence: 'Yes',
    doYouNeedToAmendTheExplosivesPrecursorsOnYourLicence: 'Yes',
    doYouHaveOrHaveYouEverHadAFirearmsLicence: 'N/A',
    doYouHaveOrHaveYouEverHadAShotgunLicence: 'N/A',
    haveYouEverHadAShotgunOrFirearmsLicenceRefusedOrRevoked: 'N/A',
    doYouHaveACriminalRecord: 'N/A',
    inTheLast10YearsHaveYouSeenADoctor: 'N/A',
    haveYouEverHadOrReceivedTreatmentForAnyDrugOrAlcoholrelatedHealthProblems: 'N/A',
    doesYourLicenceNeedToCoverExplosivesPrecursors: 'N/A',
    selectAnExplosivesPrecursor: 'Sodium perchlorate above 40% (weight by weight)',
    whereWillYouStoreTheAmmoniumNitrate: 'Home address',
    whereWillYouUseTheAmmoniumNitrate: 'Other address',
    doYouNeedToAmendThePoisonsOnYourLicence: 'Yes',
    doYouWantToContinueTheFormWithoutChangingTheEpp: 'Yes',
    doesYourLicenceNeedToCoverPoisons: 'N/A',
    tellUsWhichPoisonsYouWantToImportAcquireUseOrPossess: 'Bromomethane',
    whereWillYouUseTheDnp: 'Other address',
    whereWillYouStoreTheDnp: 'Home address',
    whatIsYourCountersignatorysIdentityDocument: 'Passport from the EU, Switzerland, Norway, Iceland or Liechtenstein',
  }, '7'),
  '8': S({
    whatTypeOfApplicationDoYouNeedToMake: 'Amend a licence',
    haveYouEverUsedAnyOtherNames: 'N/A',
    whyDoYouNeedAReplacementLicence: 'N/A',
    haveYouReportedTheTheftToPolice: 'N/A',
    haveAnyOfYourDetailsChangedSinceLicence: 'N/A',
    doYouNeedToAmendYourNameOnTheLicence: 'No',
    doYouHaveMoreThanOneNationality: 'N/A',
    whatIsYourSex: 'N/A',
    whichIdentityDocumentDoYouWantToUse: 'UK driving licence',
    doYouNeedToAmendYourHomeAddressOnTheLicence: 'Yes',
    doYouNeedToAmendTheSubstanceOnYourLicence: 'No',
    doYouNeedToAmendTheExplosivesPrecursorsOnYourLicence: 'No',
    doYouHaveOrHaveYouEverHadAFirearmsLicence: 'N/A',
    doYouHaveOrHaveYouEverHadAShotgunLicence: 'N/A',
    haveYouEverHadAShotgunOrFirearmsLicenceRefusedOrRevoked: 'N/A',
    doYouHaveACriminalRecord: 'N/A',
    inTheLast10YearsHaveYouSeenADoctor: 'N/A',
    haveYouEverHadOrReceivedTreatmentForAnyDrugOrAlcoholrelatedHealthProblems: 'N/A',
    doesYourLicenceNeedToCoverExplosivesPrecursors: 'N/A',
    selectAnExplosivesPrecursor: 'N/A',
    whereWillYouStoreTheAmmoniumNitrate: 'N/A',
    whereWillYouUseTheAmmoniumNitrate: 'N/A',
    doYouNeedToAmendThePoisonsOnYourLicence: 'No',
    doYouWantToContinueTheFormWithoutChangingTheEpp: 'No',
    doesYourLicenceNeedToCoverPoisons: 'N/A',
    tellUsWhichPoisonsYouWantToImportAcquireUseOrPossess: 'Mercury and its compounds',
    whereWillYouUseTheDnp: 'Home address',
    whereWillYouStoreTheDnp: 'Other address',
    whatIsYourCountersignatorysIdentityDocument: 'UK driving licence',
  }, '8'),
  '9': S({
    whatTypeOfApplicationDoYouNeedToMake: 'Replace a licence',
    haveYouEverUsedAnyOtherNames: 'N/A',
    whyDoYouNeedAReplacementLicence: 'Licence was stolen',
    haveYouReportedTheTheftToPolice: 'Yes',
    haveAnyOfYourDetailsChangedSinceLicence: 'Yes',
    doYouNeedToAmendYourNameOnTheLicence: 'Yes',
    doYouHaveMoreThanOneNationality: 'N/A',
    whatIsYourSex: 'N/A',
    whichIdentityDocumentDoYouWantToUse: 'Passport from the EU, Switzerland, Norway, Iceland or Liechtenstein',
    doYouNeedToAmendYourHomeAddressOnTheLicence: 'Yes',
    doYouNeedToAmendTheSubstanceOnYourLicence: 'Yes',
    doYouNeedToAmendTheExplosivesPrecursorsOnYourLicence: 'Yes',
    doYouHaveOrHaveYouEverHadAFirearmsLicence: 'N/A',
    doYouHaveOrHaveYouEverHadAShotgunLicence: 'N/A',
    haveYouEverHadAShotgunOrFirearmsLicenceRefusedOrRevoked: 'N/A',
    doYouHaveACriminalRecord: 'N/A',
    inTheLast10YearsHaveYouSeenADoctor: 'N/A',
    haveYouEverHadOrReceivedTreatmentForAnyDrugOrAlcoholrelatedHealthProblems: 'N/A',
    doesYourLicenceNeedToCoverExplosivesPrecursors: 'N/A',
    selectAnExplosivesPrecursor: 'Nitromethane above 30% (weight by weight)',
    whereWillYouStoreTheAmmoniumNitrate: 'Home address',
    whereWillYouUseTheAmmoniumNitrate: 'Other address',
    doYouNeedToAmendThePoisonsOnYourLicence: 'Yes',
    doYouWantToContinueTheFormWithoutChangingTheEpp: 'N/A',
    doesYourLicenceNeedToCoverPoisons: 'N/A',
    tellUsWhichPoisonsYouWantToImportAcquireUseOrPossess: 'Thallium and its salts',
    whereWillYouUseTheDnp: 'Other address',
    whereWillYouStoreTheDnp: 'Home address',
    whatIsYourCountersignatorysIdentityDocument: 'British passport',
  }, '9'),
  '10': S({
    whatTypeOfApplicationDoYouNeedToMake: 'Replace a licence',
    haveYouEverUsedAnyOtherNames: 'N/A',
    whyDoYouNeedAReplacementLicence: 'Licence is lost',
    haveYouReportedTheTheftToPolice: 'No',
    haveAnyOfYourDetailsChangedSinceLicence: 'No',
    doYouNeedToAmendYourNameOnTheLicence: 'No',
    doYouHaveMoreThanOneNationality: 'N/A',
    whatIsYourSex: 'N/A',
    whichIdentityDocumentDoYouWantToUse: 'British passport',
    doYouNeedToAmendYourHomeAddressOnTheLicence: 'No',
    doYouNeedToAmendTheSubstanceOnYourLicence: 'No',
    doYouNeedToAmendTheExplosivesPrecursorsOnYourLicence: 'No',
    doYouHaveOrHaveYouEverHadAFirearmsLicence: 'N/A',
    doYouHaveOrHaveYouEverHadAShotgunLicence: 'N/A',
    haveYouEverHadAShotgunOrFirearmsLicenceRefusedOrRevoked: 'N/A',
    doYouHaveACriminalRecord: 'N/A',
    inTheLast10YearsHaveYouSeenADoctor: 'N/A',
    haveYouEverHadOrReceivedTreatmentForAnyDrugOrAlcoholrelatedHealthProblems: 'N/A',
    doesYourLicenceNeedToCoverExplosivesPrecursors: 'N/A',
    selectAnExplosivesPrecursor: 'Sulfuric acid above 15% (weight by weight)',
    whereWillYouStoreTheAmmoniumNitrate: 'Other address',
    whereWillYouUseTheAmmoniumNitrate: 'Home address',
    doYouNeedToAmendThePoisonsOnYourLicence: 'No',
    doYouWantToContinueTheFormWithoutChangingTheEpp: 'N/A',
    doesYourLicenceNeedToCoverPoisons: 'N/A',
    tellUsWhichPoisonsYouWantToImportAcquireUseOrPossess: 'Zinc phosphide',
    whereWillYouUseTheDnp: 'Home address',
    whereWillYouStoreTheDnp: 'Other address',
    whatIsYourCountersignatorysIdentityDocument: 'EEA passport',
  }, '10'),
  '11': S({
    whatTypeOfApplicationDoYouNeedToMake: 'Replace a licence',
    haveYouEverUsedAnyOtherNames: 'N/A',
    whyDoYouNeedAReplacementLicence: 'Licence is damaged',
    haveYouReportedTheTheftToPolice: 'No',
    haveAnyOfYourDetailsChangedSinceLicence: 'Yes',
    doYouNeedToAmendYourNameOnTheLicence: 'No',
    doYouHaveMoreThanOneNationality: 'N/A',
    whatIsYourSex: 'N/A',
    whichIdentityDocumentDoYouWantToUse: 'UK driving licence',
    doYouNeedToAmendYourHomeAddressOnTheLicence: 'Yes',
    doYouNeedToAmendTheSubstanceOnYourLicence: 'No',
    doYouNeedToAmendTheExplosivesPrecursorsOnYourLicence: 'Yes',
    doYouHaveOrHaveYouEverHadAFirearmsLicence: 'N/A',
    doYouHaveOrHaveYouEverHadAShotgunLicence: 'N/A',
    haveYouEverHadAShotgunOrFirearmsLicenceRefusedOrRevoked: 'N/A',
    doYouHaveACriminalRecord: 'N/A',
    inTheLast10YearsHaveYouSeenADoctor: 'N/A',
    haveYouEverHadOrReceivedTreatmentForAnyDrugOrAlcoholrelatedHealthProblems: 'N/A',
    doesYourLicenceNeedToCoverExplosivesPrecursors: 'N/A',
    selectAnExplosivesPrecursor: 'Phosphoric acid above 30% (weight by weight)',
    whereWillYouStoreTheAmmoniumNitrate: 'Home address',
    whereWillYouUseTheAmmoniumNitrate: 'Other address',
    doYouNeedToAmendThePoisonsOnYourLicence: 'Yes',
    doYouWantToContinueTheFormWithoutChangingTheEpp: 'N/A',
    doesYourLicenceNeedToCoverPoisons: 'N/A',
    tellUsWhichPoisonsYouWantToImportAcquireUseOrPossess: 'Chloropicrin',
    whereWillYouUseTheDnp: 'Other address',
    whereWillYouStoreTheDnp: 'Home address',
    whatIsYourCountersignatorysIdentityDocument: 'UK driving licence',
  }, '11'),
};

export function getEppScenarioData(scenarioId: string): EppScenarioData {
  const data = scenarios[scenarioId];
  if (!data) {
    throw new Error(`No EPP scenario data found for scenario id ${scenarioId}`);
  }
  return data;
}
